package com.project.dchat.Entities;

public enum MessageType{
    FILE,
    STRING,
    IMAGE,
    CODE,
    EXCISTS_REQUEST,
    EXCISTS_RESPONSE,
    ACTIVATE_ACCOUNT,
    LOGIN_REQUEST,
    LOGIN_RESPONSE_ACCESS_GRANTED,
    LOGIN_RESPONSE_ACCESS_DENIED,
    LOGIN_RESPONSE_NOT_VERIFIED,
    NOTIFICATION,
    REMEMBER_PASSWORD,
    REMEMBER_PASSWORD_RESPONSE,
    RESET_PASSWORD,
    RESTORE_REQUEST_VERIFIED,
    CHANGE_PASSWORD,
    CHANGE_PASSWORD_CHANGED
}
